service: aws-lunch

provider:
  name: aws
  runtime: nodejs4.3

functions:
  menu:
    handler: handler.menu
    events:
      - http:
          path: menu
          method: get

plugins:
  - serverless-offline
