service: aws-lunch

provider:
  name: aws
  runtime: nodejs4.3

functions:
  menu:
    handler: market_creations/functions.menu
    events:
      - http:
          path: market_creations/menu
          method: get
  trucks:
    handler: walnut_wednesday/functions.trucks
    events:
      - http:
          path: walnut_wednesday/trucks
          method: get

plugins:
  - serverless-offline
